name: PulseOximeter
options:
  bundleIdPrefix: com.example
  deploymentTarget: "14.0"
  
targets:
  PulseOximeter:
    type: application
    platform: iOS
    sources:
      - src
    info:
      path: src/Info.plist
      properties:
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UIMainStoryboardFile: ""
        UILaunchStoryboardName: LaunchScreen
